### ISSUE TITLE
Pytorch not available for Installing 

### ISSUE THREAD

**Issue by GaurDev06** [voize-gmbh/pytorch-lite-multiplatform#12] opened 2022-06-29 11:25 UTC
Hi there,
I am working on KMM project and want to implement pytorch in my kmm but getting error

Could not resolve de.voize:pytorch-lite-multiplatform:0.3.3.
Required by:
    project :shared

**Comment by Legion2** [comment] 2022-06-29 14:31
The project is published to maven central https://search.maven.org/artifact/de.voize/pytorch-lite-multiplatform/0.3.3/jar. Make sure you include maven central repository in your build config.

**Comment by GaurDev06** [comment] 2022-06-30 04:29
Hi, Thanks for following up on this and for your response.
I also included the maven like this
buildscript {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
    dependencies {
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.0")
        classpath("com.android.tools.build:gradle:7.2.1")
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

tasks.register("clean", Delete::class) {
    delete(rootProject.buildDir)
}
Is there anything wrong?

**Comment by Legion2** [comment] 2022-06-30 09:08
No this looks right, I created a test project using a basic koltin multiplatform project setup and added your config.

Then I added to `app/build.gradle.kts`:
```
kotlin {
    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation("de.voize:pytorch-lite-multiplatform:0.4.0") // added this
            }
        }
    }
}
```

And this works fine.

**Comment by GaurDev06** [comment] 2022-06-30 09:35
HI @Legion2 
I am trying in same way 
sourceSets {
        val commonMain by getting{
            dependencies {
                implementation("com.soywiz.korlibs.korim:korim:$korimVersion")
                implementation("org.jetbrains.kotlin:kotlin-stdlib-common")
                implementation( "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutineVersion")
                implementation("de.voize:pytorch-lite-multiplatform:0.4.0")

            }
        }
But its showing error
Could not resolve de.voize:pytorch-lite-multiplatform:0.4.0.

**Comment by Legion2** [comment] 2022-06-30 10:26
@GaurDev06 can you share your complete project (is is open source on github), so we can reproduce the problem?

**Comment by GaurDev06** [comment] 2022-06-30 14:56
@Legion2  
please find the with the help of given link.
https://github.com/GaurDev06/ApplicationDemo.git
Thanks

**Comment by Legion2** [comment] 2022-06-30 15:04
I have checked out your project and can run `./gradlew build` and `./gradlew installDebug` on my linux without problems. Which command results in the error?

**Comment by Legion2** [comment] 2022-07-01 11:29
I will test on a mac next week.

**Comment by GaurDev06** [comment] 2022-07-01 11:35
@Legion2 
Thank for the update.
And waiting for your response.
TIA

**Comment by erksch** [comment] 2022-07-04 22:23
@GaurDev06 

With your repo I get the following error on a M1 MacBook Pro on `./gradlew build`.

This is because a blank Kotlin Multiplatform Project includes a [`iosSimulatorArm64`](https://github.com/GaurDev06/ApplicationDemo/blob/master/shared/build.gradle.kts#L13) target but this library currently does not support this target. If you remove the target it works fine for me.

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':shared:linkPodDebugFrameworkIosSimulatorArm64'.
> Could not resolve all task dependencies for configuration ':shared:iosSimulatorArm64CompileKlibraries'.
   > Could not resolve de.voize:pytorch-lite-multiplatform:0.4.0.
     Required by:
         project :shared
      > No matching variant of de.voize:pytorch-lite-multiplatform:0.4.0 was found. The consumer was configured to find a usage of 'kotlin-api' of a library, preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native', attribute 'org.jetbrains.kotlin.native.target' with value 'ios_simulator_arm64' but:
          - Variant 'iosArm64ApiElements-published' capability de.voize:pytorch-lite-multiplatform:0.4.0 declares a usage of 'kotlin-api' of a library, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_arm64' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_simulator_arm64'
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Variant 'iosArm64MetadataElements-published' capability de.voize:pytorch-lite-multiplatform:0.4.0 declares a library, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
              - Incompatible because this component declares a usage of 'kotlin-metadata' of a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_arm64' and the consumer needed a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_simulator_arm64'
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Variant 'iosX64ApiElements-published' capability de.voize:pytorch-lite-multiplatform:0.4.0 declares a usage of 'kotlin-api' of a library, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_x64' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_simulator_arm64'
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Variant 'iosX64MetadataElements-published' capability de.voize:pytorch-lite-multiplatform:0.4.0 declares a library, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
              - Incompatible because this component declares a usage of 'kotlin-metadata' of a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_x64' and the consumer needed a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_simulator_arm64'
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Variant 'metadataApiElements' capability de.voize:pytorch-lite-multiplatform:0.4.0 declares a library:
              - Incompatible because this component declares a usage of 'kotlin-metadata' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'common' and the consumer needed a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_simulator_arm64')
          - Variant 'releaseApiElements-published' capability de.voize:pytorch-lite-multiplatform:0.4.0 declares an API of a library:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_simulator_arm64')
          - Variant 'releaseRuntimeElements-published' capability de.voize:pytorch-lite-multiplatform:0.4.0 declares a runtime of a library:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'ios_simulator_arm64')
```

**Comment by Legion2** [comment] 2022-07-04 22:42
@erksch we should add the `iosSimulatorArm64()` target, we just need to add it to gradle and publish I think

**Comment by GaurDev06** [comment] 2022-07-05 07:06
Hi @erksch Thanks for the Update and your time but when we install it without the iosSimulatorArm64() and iosSimulatorArmX64 then we are not able to run the application in the xcode it's showing error like
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_TorchModule", referenced from:
      objc-class-ref in shared(result.o)
      objc-class-ref in shared(result.o)
  "_OBJC_CLASS_$_Tensor", referenced from:
      objc-class-ref in shared(result.o)
      objc-class-ref in shared(result.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
So if there any other way then please let us know.
thanks again for your efforts.

**Comment by erksch** [comment] 2022-07-05 07:54
You seem to not have included the PLMLibTorchWrapper pod correctly. Please check out the updated README.

**Comment by erksch** [comment] 2022-07-05 10:04
remove the  `iosSimulatorArm64()` target

**Comment by GaurDev06** [comment] 2022-07-05 12:11
Hi @erksch,
Thanks for your response,
I have removed the iosSimulatorArm64() from gradle and successfullly build the kmm gradle but in IOS Xcode getting the below error
<img width="1133" alt="Screenshot 2022-07-05 at 5 34 58 PM" src="https://user-images.githubusercontent.com/106970927/177324161-3459bb5d-22c5-408d-8e4a-f7bf85038abc.png">

**Comment by GaurDev06** [comment] 2022-07-05 13:01
Hi @erksch Thanks for your fast response ,
I used the same "# use_frameworks!" but for commenting here i used that because it will show you the heading when i will post it

**Comment by GaurDev06** [comment] 2022-07-06 04:50
Hi @erksch,

shared/shared.podspec content is 

**Pod::Spec.new do |spec|
    spec.name                     = 'shared'
    spec.version                  = '1.0'
    spec.homepage                 = 'https://github.com/voize-gmbh/pytorch-lite-multiplatform'
    spec.source                   = { :http=> ''}
    spec.authors                  = ''
    spec.license                  = ''
    spec.summary                  = 'Kotlin Multiplatform wrapper for PyTorch Lite'
    spec.vendored_frameworks      = 'build/cocoapods/framework/shared.framework'
    spec.libraries                = 'c++'
    spec.ios.deployment_target = '13.5'
    spec.dependency 'PLMLibTorchWrapper', '0.4.0'
                
    spec.pod_target_xcconfig = {
        'KOTLIN_PROJECT_PATH' => ':shared',
        'PRODUCT_MODULE_NAME' => 'shared',
    }
                
    spec.script_phases = [
        {
            :name => 'Build shared',
            :execution_position => :before_compile,
            :shell_path => '/bin/sh',
            :script => <<-SCRIPT
                if [ "YES" = "$COCOAPODS_SKIP_KOTLIN_BUILD" ]; then
                  echo "Skipping Gradle build task invocation due to COCOAPODS_SKIP_KOTLIN_BUILD environment variable set to \"YES\""
                  exit 0
                fi
                set -ev
                REPO_ROOT="$PODS_TARGET_SRCROOT"
                "$REPO_ROOT/../gradlew" -p "$REPO_ROOT" $KOTLIN_PROJECT_PATH:syncFramework \
                    -Pkotlin.native.cocoapods.platform=$PLATFORM_NAME \
                    -Pkotlin.native.cocoapods.archs="$ARCHS" \
                    -Pkotlin.native.cocoapods.configuration="$CONFIGURATION"
            SCRIPT
        }
    ]
                
end**

And iosApp/Pods file is given below...

<img width="687" alt="Screenshot 2022-07-06 at 10 19 25 AM" src="https://user-images.githubusercontent.com/106970927/177471081-2cfb0bc9-8e67-461a-b397-dfb00e039c1a.png">

**Comment by GaurDev06** [comment] 2022-07-07 04:50
ok will send you ASAp

**Comment by GaurDev06** [comment] 2022-07-08 10:11
Hi @erksch,
Please find the file for your reference [](url) https://github.com/GaurDev06/DemoApp.git

**Comment by erksch** [comment] 2022-07-08 10:39
@GaurDev06 thanks, I checked out your repo. First thing, `iosApp/Pods` should be in your `.gitignore`, the folder is autogenerated.

Regarding your issue, please try to delete the `iosApp/Pods` folder, run `cd iosApp && pod install` and try to build the app again.

**Comment by erksch** [comment] 2022-07-31 22:40
Closing

**Closed by erksch** 2022-07-31 22:40 UTC
Labels: help wanted
